name: run-integration-tests-actions
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x, 12.x,14.x]
                mongodb-version: [4.x]

        steps:
            - name: Git checkout
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
            
            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.3.0
              with:
                mongodb-version: ${{ matrix.mongodb-version }}

            - run: yarn

            - run: yarn test
                env:
                  DATABASE_URL: mongodb+srv://me:e5Px5NfyaqivEwt@cluster0-unnnh.gcp.mongodb.net/ninthWk
                  SECRET_KEY: mykeycode
